#!/bin/bash
set -x
set -e

PASSWORD=${PASSWORD:-123456}
SERVER_PORT=${SERVER_PORT:-8388}
ENCRYPT_METHOD=${ENCRYPT_METHOD:-"aes-256-cfb"}

/usr/bin/ssserver -p ${SERVER_PORT} -k ${PASSWORD} -m ${ENCRYPT_METHOD}